spring:
  application:
    name: ${SPRING_APPLICATION_NAME:library}

  boot:
    admin:
      client:
        url: ${BOOT_ADMIN_CLIENT_URL:http://localhost:9000}
        instance:
          metadata:
            user:
              name: ${BOOT_ADMIN_CLIENT_INSTANCE_METADATA_USER:uexcel@gmail.com}
              password: ${BOOT_ADMIN_CLIENT_INSTANCE_METADATA_PASSWORD:1234}
  config:
    activate:
      on-profile: prod

logging:
  level:
    com.uexcel: ${LOGGING_LEVEL_COM_UEXCEL:error}
management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true

employee:
  firstName: ${FIRST_NAME:Steven}
  lastName: ${LAST_NAME:Jokin}
  phoneNumber : ${PHONE_NUMBER:09088108115}
  email: ${EMAIL:steven@yahoo.com}
  password: ${PASSWORD:steven}
  role: ${ROLE:ADMIN}

info:
  app:
    name: library
    description: "Wisdom Spring Library"
    version: "0.0.1"


