spring:
  application:
    name: ${SPRING_APPLICATION_NAME:library}
  datasource:
    url: ${DATABASE_URL:jdbc:h2:mem:testdb}
    driver-class-name: ${DRIVER_CLASS_NAME:org.h2.Driver}
    username: ${DATABASE_USERNAME:admin}
    password: ${DATABASE_PASSWORD:}
  jpa:
    defer-datasource-initialization: true


  data:
    rest:
      base-path: "/data-api"

  boot:
    admin:
      client:
        url: ${BOOT_ADMIN_CLIENT_URL:http://localhost:9000}
        instance:
          metadata:
            user:
              name: ${BOOT_ADMIN_CLIENT_INSTANCE_METADATA_USER:uexcel@gmail.com}
              password: ${BOOT_ADMIN_CLIENT_INSTANCE_METADATA_PASSWORD:1234}
  config:
    import: application_prod.yml
  profiles:
    active: prod

logging:
  level:
    com.uexcel: ${LOGGING_LEVEL_COM_UEXCEL:DEBUG}
management:
  endpoints:
    web:
      exposure:
        include: ${MANAGEMENT_ENDPOINTS_WEB_EXPOSURE:*}

  info:
    env:
      enabled: true

employee:
  firstName: ${FIRST_NAME:Steven}
  lastName: ${LAST_NAME:Jokin}
  phoneNumber : ${PHONE_NUMBER:09088108115}
  email: ${EMAIL:steven@yahoo.com}
  password: ${PASSWORD:steven}
  role: ${ROLE:ADMIN}

info:
  app:
    name: library
    description: "Wisdom Spring Library"
    version: "0.0.1"
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    csrf:
      enabled: true

