spring:
  application:
    name: library
  datasource:
    url: "jdbc:h2:mem:testdb"
    driver-class-name: org.h2.Driver
    username: "admin"
    password: ""
  jpa:
    defer-datasource-initialization: true

  data:
    rest:
      base-path: "/data-api"

  boot:
    admin:
      client:
        url: http://localhost:9000
        instance:
          metadata:
            user:
              name: uexcel@gmail.com
              password: 1234

logging:
  level:
    com.uexcel: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: "*"

  info:
    env:
      enabled: true


employee:
  firstName: "Steven"
  lastName: "Jokin"
  phoneNumber : "09088108115"
  email: "steven@yahoo.com"
  password: "steven"
  role: "ADMIN"

info:
  app:
    name: library
    description: "Wisdom Spring Library"
    version: "0.0.1"

