spring:
  application:
    name: library
  datasource:
    url: "jdbc:h2:mem:testdb"
    driver-class-name: org.h2.Driver
    username: "admin"
    password: ""
  jpa:
    defer-datasource-initialization: true

logging:
  level:
    com.uexcel: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: health
#springdoc:
#  api-docs:
#    enabled: true
#  show-actuator: true

employee:
  firstName: "Steven"
  lastName: "Jokin"
  phoneNumber : "09088108115"
  email: "steven@yahoo.com"
  password: "steven"
  role: "ADMIN"